backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  #name: github
  #repo: huidengvan/site1 # Path to your GitHub repository
  #branch: master

# This line should *not* be indented
#publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: "static/up/posts" # Media files will be stored in the repo under static/images/uploads
public_folder: "/up/posts" # The src attribute for uploaded media will begin with /images/uploads

collections: # A list of collections the CMS should be able to edit
  - name: 'posts' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Posts' # Used in the UI
    label_singular: 'Post' # Used in the UI, ie: "New Post"
    description: >
      Edit posts.
    folder: 'content/posts'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    summary: '{{title}} -- {{year}}/{{month}}/{{day}}'
    sortableFields: ['commit_date', 'title', 'commit_author', 'language.en']
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          dateFormat: 'YYYY-MM-DD',
          timeFormat: 'HH:mm:ss',
          format: 'YYYY-MM-DD HH:mm:ssZ',
        }
      - label: "Categories"
        name: "categories"
        widget: "list"
        default: ["news"]
      - label: "Tags"
        name: "tags"
        widget: "list"
        default: ["activity"]
      - {
          label: 'Attachments (Once uploaded/selected, you can copy the link from preview panel to body windown below)',
          name: 'attachments',
          widget: 'file',
          required: false,
          media_library: {config: {multiple: true}}
        }
      - { label: 'Body', name: 'body', widget: 'markdown', hint: 'Main content goes here.' }

    meta:
      - { label: 'SEO Description', name: 'description', widget: 'text' }